// src/redux/types.js

// <----------- Astrologer Get Profile -------------->
export const FETCH_ASTRO_PROFILE_REQUEST = 'FETCH_ASTRO_PROFILE_REQUEST';
export const FETCH_ASTRO_PROFILE_SUCCESS = 'FETCH_ASTRO_PROFILE_SUCCESS';
export const FETCH_ASTRO_PROFILE_FAILURE = 'FETCH_ASTRO_PROFILE_FAILURE';

// <----------- Astrologer Get Profile -------------->
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

export const FETCH_CART_LIST_REQUEST = "FETCH_CART_LIST_REQUEST";
export const FETCH_CART_LIST_SUCCESS = "FETCH_CART_LIST_SUCCESS";
export const FETCH_CART_LIST_FAILURE = "FETCH_CART_LIST_FAILURE";

export const UPDATE_CART_ITEM_REQUEST = "UPDATE_CART_ITEM_REQUEST";
export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM_FAILURE = "UPDATE_CART_ITEM_FAILURE";

export const REMOVE_CART_ITEM_REQUEST = "REMOVE_CART_ITEM_REQUEST";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAILURE = "REMOVE_CART_ITEM_FAILURE";
